### PR TITLE
Prevent double call of async callback

### PR DESCRIPTION
**Pull request by joeyfromspace**
## CHANGE LOG

- Wraps the async series callback in harvester in another function to prevent double calls

## NOTES

This is to address uncaught exceptions that we've been seeing after upgrading to NR agent 4.X from 1.X.

While this Pull Request does not address the root cause of the double callbacks (I think someone with more experience with this code base would be better suited to do that), it will prevent uncaught exceptions by ensuring that a given callback is only called once.

Here is an example stack trace that we've been seeing:

```
uncaughtException (api) Callback was already called. Error: Callback was already called. 
    at /opt/node_modules/newrelic/node_modules/async/dist/async.js:966:32 
    at afterSend (/opt/node_modules/newrelic/lib/harvest.js:156:7) 
    at ClientRequest.standardHandler (/opt/node_modules/newrelic/lib/collector/api.js:517:12) 
    at ClientRequest.emit (events.js:182:13) 
    at ClientRequest.EventEmitter.emit (domain.js:442:20) 
    at TLSSocket.socketErrorListener (_http_client.js:391:9) 
    at TLSSocket.emit (events.js:182:13) 
    at TLSSocket.EventEmitter.emit (domain.js:442:20) 
    at TLSSocket._emitTLSError (_tls_wrap.js:606:10) 
    at TLSWrap.onerror (_tls_wrap.js:268:11)
```

### CODE REVIEW

**Comment by NatalieWolfe** [comment]
Thanks for this contribution! We've just recently cleaned up a lot of the harvest/collector code and are about to release those changes (holiday season may cause delays, of course). This may resolve the underlying issue, and will definitely cause a conflict with this PR.

Once these changes are released, and if they don't resolve your issue, then we will look into taking this PR.

**Comment by 3z3qu13l** [comment]
@joeyfromspace could you rebase with latest 4.13.0 to check ?

**Comment by joeyfromspace** [comment]
@3z3qu13l Done!

**Comment by 3z3qu13l** [comment]
We just got it 3 times today on different apps

With version **4.10.0**:
`Error: Callback was already called.,     at /var/www/node_modules/async/dist/async.js:966:32,     at onMetricData (/var/www/node_modules/newrelic/lib/harvest.js:274:16),     at ClientRequest.standardHandler (/var/www/node_modules/newrelic/lib/collector/api.js:464:12),     at ClientRequest.emit (events.js:182:13),     at TLSSocket.socketErrorListener (_http_client.js:391:9),     at TLSSocket.emit (events.js:182:13),     at TLSSocket._emitTLSError (_tls_wrap.js:606:10),     at TLSWrap.onerror (_tls_wrap.js:268:11)`

With version **4.11.0**:
`Error: Callback was already called.,     at /var/www/node_modules/async/dist/async.js:966:32,     at onAnalyticsEvents (/var/www/node_modules/newrelic/lib/harvest.js:370:9),     at ClientRequest.standardHandler (/var/www/node_modules/newrelic/lib/collector/api.js:468:12),     at ClientRequest.emit (events.js:182:13),     at TLSSocket.socketErrorListener (_http_client.js:391:9),     at TLSSocket.emit (events.js:182:13),     at TLSSocket._emitTLSError (_tls_wrap.js:606:10),     at TLSWrap.onerror (_tls_wrap.js:268:11)`

I'ld like to be sure it's fixed before updating every app packages.

**Comment by NatalieWolfe** [comment]
@joeyfromspace I believe your rebase went a little wrong. I don't think you want all 134 of these commits.

**Comment by NatalieWolfe** [comment]
@3z3qu13l Have you tested with 4.13.0 yet? We just released this version yesterday and it contains a major refactoring of the collector and harvest code, the exact areas causing this problem.

I would also like to know if there were any other errors in the agent log from this time? The only reason for the callback to be executed twice would involve a connection or runtime error. Knowing specifically what caused the first callback to execute would help us determine the root cause of the double call.

**Comment by 3z3qu13l** [comment]
@NatalieWolfe
4.13.0 is probably gonna be shipped in our next release.
I'll ask for the logs on Monday.
Since I don't know how to reproduce I can't verify with certitude the latest version; maybe the logs will help me.

**Comment by NatalieWolfe** [comment]
Hey @3z3qu13l, I hope your holidays went well.

To my knowledge, the connection issue is unique to your case. I checked our incident log (available publicly here: https://status.newrelic.com/) and our maintenances. There were none that aligned with this time window.

I just looked at the support ticket you guys opened too, looks like this was resolved. Is that correct? If it hasn't could you send updated information to that ticket? Our support engineers are much better equipped to help debug these kinds of problems.

**Comment by kid-icarus** [comment]
Hi @NatalieWolfe I am also facing this issue running `4.8.1`

Here are some agent logs that correlate to the time of the double callback uncaught exception. They are fairly intermittent for us, and it seems to be related to network/tls issues.

image

image 1

**Comment by NatalieWolfe** [comment]
@kid-icarus Have you tried updating to the latest agent? There was a fairly large refactoring of the collector code after 4.8 which may resolve this.

**Comment by kid-icarus** [comment]
Hey @NatalieWolfe, I updated to the latest agent, and will report back if I encounter the issue again. Thanks :)

**Comment by NatalieWolfe** [comment]
@joeyfromspace @kid-icarus Is this still an issue for either of you with the latest agent? If not, I'll close this PR, if it is please fix this PR so it does not contain a hundred duplicated commits.

**Comment by kid-icarus** [comment]
Hey @NatalieWolfe, I just looked through logs, and after the upgrade I can see that those connection errors aren't causing problems anymore.

Thanks!

**Comment by joeyfromspace** [comment]
I haven't been able to test ourselves, but will go ahead and close this PR as it's likely going to need to be re-done anyhow if the issue persists due to the volume of changes.

Thanks!

**Pull request closed without merging**
