### PR TITLE
#316: Adds support for http/https APIs for node >= 10

### PR DESCRIPTION
**Pull request by kennethaasan**
## CHANGE LOG
- Adds support for http/https APIs for node >= 10

## NOTES
- Please see https://github.com/newrelic/node-newrelic/issues/316

### CODE REVIEW

**Comment by kennethaasan** [comment]
@nijotz, please see my comment in https://github.com/newrelic/node-newrelic/issues/316#issuecomment-567257125

This is a nock issue

**Comment by nijotz** [comment]
Ah, thank you I hadn't seen the latest comments

**Comment by nijotz** [comment]
Hi, so I did some testing, and added a test that passes a URL object as the first and only parameter, and the test fails. Is it okay with you if I continue to build on this PR and add commits?

**Comment by kennethaasan** [comment]
@nijotz, can you paste the test you wrote here? I'm not able to reproduce it.

**Comment by nijotz** [comment]
@kennethaasan Actually, it looks like there's a mix up on my end. I'm still playing with it.

**Comment by nijotz** [comment]
I added a [commit](https://github.com/newrelic/node-newrelic/pull/318/commits/77227e06d0af28c38f4ea393ef470650da5888e1) (hope you don't mind) to test different combinations of function signatures across http/https get/request. And it looks like if only a URL object is passed in as an argument, it fails. It looks like this is because [here](https://github.com/newrelic/node-newrelic/blob/77227e06d0af28c38f4ea393ef470650da5888e1/lib/instrumentation/core/http-outbound.js#L34), it checks for `_url` being a string, but if `_url` is a URL object, it doesn't do anything and `opts` is undefined. So when it gets down [here](https://github.com/newrelic/node-newrelic/blob/77227e06d0af28c38f4ea393ef470650da5888e1/lib/instrumentation/core/http-outbound.js#L135), `request.path` is `undefined` and it errors.

**Comment by nijotz** [comment]
I have time to work on this now and I can keep adding onto this PR if that is okay with you.

**Comment by kennethaasan** [comment]
That makes sense. Feel free to keep adding to this PR. I'm happy as long as it's shipped ASAP :)

**Comment by nijotz** [comment]
Hi @kennethaasan, we have an internal Github that we use. I put your commits that were on this PR on an internal branch. I added some commits to add some tests and tweak some of the code. This was released last week as 6.4.2.

[Your commit](https://github.com/newrelic/node-newrelic/commit/245b8e95532b10092c8b815e58cc361e682e3817)

[The release](https://docs.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/node-agent-642)

**Comment by nijotz** [comment]
Please let us know if you continue to have issues. Closing PR.

**Pull request closed without merging**
