### PR TITLE
The NEW_RELIC_NO_CONFIG_FILE env var is now not needed to run the agent without config file

### PR DESCRIPTION
**Pull request by carlo-808**
## Proposed Release Notes
* The `NEW_RELIC_NO_CONFIG_FILE` environment variable is no longer needed to run the agent without a configuration file.
  * If a configuration file is used with agent configuration environment variables, the environment variables will override the corresponding configuration file settings.
## Links
Closes: #627 
## Details
There are a few environment variables that do not have a corresponding configuration file setting, but those are set by the environment they run in (ie AWS Lambda).

### CODE REVIEW

**Review by michaelgoin — DISMISSED** [review]
👍 Looks good.

A couple things before mashing that merge button...

If you haven't already, I'd recommend testing with a config file that exists but is not readable in case it behaves any differently (throws for example) and make sure we handle that situation OK. As we'll now be attempting to load the config file regardless, when we would not before.

On that note, we've completed removed the variable. Just stating out loud we could have (or could still) keep it for preventing even attempting to load the file. In theory, attempting to load that file should not be expensive... so guessing not critical.

And to these points, there is a potential change in behavior where customers with the ENV var set, that also had a local config file, may get some settings from that local config file they were not before. Seems pretty low risk but it is a possibility.

**Comment by carlo-808** [comment]
Good point @michaelgoin , I'll test out the case you mentioned regarding an unreadable config file.

> On that note, we've completed removed the variable. Just stating out loud we could have (or could still) keep it for preventing even attempting to load the file. In theory, attempting to load that file should not be expensive... so guessing not critical.

Maybe I should leave the variable `NEW_RELIC_NO_CONFIG_FILE` read in there and log something about it being ignored?

> And to these points, there is a potential change in behavior where customers with the ENV var set, that also had a local config file, may get some settings from that local config file they were not before. Seems pretty low risk but it is a possibility.

I could add more information to the log message to this point. What do you think?

**Comment by carlo-808** [comment]
Good call, I'm going to bring the NEW_RELIC_NO_CONFIG_FILE check back and have it only enforce no config file. 👍

**Comment by carlo-808** [comment]
@michaelgoin It looks like we handle the error from a bad config file gracefully and disable the agent even if environment variables are set, so I think we are good there.
Error message from stdout is:
```
New Relic for Node.js is disabled due to an error:
Error: Unable to read configuration file "/location/of/newrelic.js".
```

**Comment by michaelgoin** [comment]
@carlo-808 that actually seems bad to me that we disable the agent given we are trying to move away from it being required if you don't set a special ENV var.

**Comment by carlo-808** [comment]
Do you think we should just log a warning that the config file is unreadable in this case and try to start the agent?

**Comment by michaelgoin** [comment]
@carlo-808 yeah, i think logging a warning that we were unable to read the config file and that we are attempting to fall back to ENV vars.

**Review by michaelgoin — APPROVED** [review]
👍 looks good.

**Pull request merged**
