### PR TITLE
Added missing concat-stream package

### PR DESCRIPTION
**Pull request by shadone**

### CODE REVIEW

**Comment by shadone** [comment]
The latest released version of node-newrelic v1.21.0 introduced a bug that completely breaks new relic monitoring:

Here is what we see on startup:

```
New Relic for Node.js was unable to bootstrap itself due to an error:
Error: Cannot find module 'concat-stream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/app/current/node_modules/newrelic/lib/aws-info.js:6:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by shadone** [comment]
I've also created a support request #153194 regarding this issue.

**Comment by Awk34** [comment]
that's a strange-looking commit

**Comment by shadone** [comment]
I've added the package with `npm install --save concat-stream` which reorders packages to be alphabetically sorted (which I believe is a standard introduced last(?) year in npm tool).

**Comment by Awk34** [comment]
:P yeah I figured. GitHub interprets it strangely too, the first line change

**Comment by wraithan** [comment]
We'll likely not use this PR as we'll need to add the license to specific files to make sure tests pass (We have tests to make sure our dependencies' license hasn't changed). We've unpublished the bad version and will be publishing a new one early next week with everything corrected.

**Pull request closed without merging**
