### PR TITLE
refactor: change dynamic import to work with bundlers

### LINKED ISSUE #1904: Modify the dynamic import of api.js and stub_api.js to better work with bundlers
## Is your feature request related to a problem? Please describe.
The way that initApi passes the path for `api.js` and `stub_api.js` does not work well with bundlers like Rollup or Vite.

## Feature Description
Move the path to the require statement in `initApi`.  See [patch](https://github.com/newrelic/node-newrelic/compare/main...atodd:node-newrelic:feat/improve-bundling)

## Describe Alternatives
https://github.com/newrelic/node-newrelic/compare/main...atodd:node-newrelic:feat/improve-bundling

## Priority
Please help us better understand this feature request by choosing a priority from the following options: Blocker

This is blocking my upgrade to v11.

### PR DESCRIPTION
**Pull request by atodd**
Moving the './' path to the require statement allows bundlers to find the api.js and stub_api.js files

## Description

Move path for api dynamic import to require statement in `initApi`.

## Related Issues

Closes #1904

### CODE REVIEW

**Comment by jsumners-nr** [comment]
👋  thank you for the contribution. It looks like it should work correctly, but Node v18.19.0 has introduced an issue in our CI. I have a PR out to an upstream module solve that problem and we can hopefully get it dealt with soon.

**Comment by jsumners-nr** [comment]
The fix has been landed in our repo. @atodd can you rebase your branch please?

**Comment by bizob2828** [comment]
@atodd just for my own edification can you explain your fix? Your change just moves the `./` to be hardcoded in the require.  Does your bundler configuration look for something `./${apiPath}`? If so, why can't it just look for `apiPath`? Is it because it's too ambiguous?

**Comment by atodd** [comment]
@bizob2828 My understanding (at least for the bundlers I have used, mainly Vite and Webpack) is that `require($apiPath)` is too ambiguous because the bundlers can not determine the value of `$apiPath`.  However, adding the `./` tells the bundler what directory a file will be dynamically imported from.

**Review by jsumners-nr — APPROVED** [review]

**Pull request merged**
