### PR TITLE
fix: Mark message consumer Transaction as error if the consumer Promise is rejected

### PR DESCRIPTION
**Pull request by benney-au-le**
## Description

See here for sample instrumentation.
https://gist.github.com/benney-au-le/df32c78c2777a1166917d3b67665d76d

## How to Test

Please describe how you have tested these changes. Have you run the code against an example application?
What steps did you take to ensure that the changes are working correctly?
I used the gist above to instrument and check using NRQL

## Related Issues

- https://forum.newrelic.com/s/hubtopic/aAX8W00000006FIWAY/instrumenting-messages-not-recording-errors?t=1684112114470

### CODE REVIEW

**Comment by bizob2828** [comment]
@benney-au-le thanks for the PR. I plan on taking a look at it this week

**Comment by benney-au-le** [comment]
> @benney-au-le thanks for the PR. I plan on taking a look at it this week. However before I even look can you write some tests that prove out this new code please?

Yea I can have a look at writing tests. However I'm not sure which file to write the tests in

**Comment by bizob2828** [comment]
> > @benney-au-le thanks for the PR. I plan on taking a look at it this week. However before I even look can you write some tests that prove out this new code please?
> 
> Yea I can have a look at writing tests. However I'm not sure where to write the tests. Can you point me to the right place?

@benney-au-le they should go in the [messsage-shim unit tests](https://github.com/newrelic/node-newrelic/blob/main/test/unit/shim/message-shim.test.js)

**Comment by benney-au-le** [comment]
> > > @benney-au-le thanks for the PR. I plan on taking a look at it this week. However before I even look can you write some tests that prove out this new code please?
> > 
> > 
> > Yea I can have a look at writing tests. However I'm not sure where to write the tests. Can you point me to the right place?
> 
> @benney-au-le they should go in the [messsage-shim unit tests](https://github.com/newrelic/node-newrelic/blob/main/test/unit/shim/message-shim.test.js)

@bizob2828 thanks.
I've added a test.

**Comment by benney-au-le** [comment]
> @benney-au-le after taking a look at this, I'm not sure this is something we can accept. I see what you're trying to do but by making the change where you did it's a breaking change. Up until now errors are not being handled by the message shim. We typically put the onus on our customers. We do have global unhandled and uncaught rejection handlers but I think it's not hitting that path because bull is catching all errors [here](https://github.com/OptimalBits/bull/blob/develop/lib/queue.js#L1177) . You can see by my [updated example](https://gist.github.com/bizob2828/1f38b55d4b96fae69b0a89acae9c3ffe#file-bull-instrumentation-js-L67) of your gist, how we recommend our customers handle something like this. I tried to propose a more holistic solution which was to listen for the failed even on the queue but the transaction is getting ended in the message shim, so something like this will not work
> 
> ```js
>   shim.wrap(Queue.prototype, 'emit', function wrapEmit(shim, origEmit, name, args) {
>     return function wrappedEmit() {
>       const args = shim.argsToArray.apply(shim, arguments)
>       if (args[0] === 'failed') {
>         const err = args[2]
>         newrelic.noticeError()
>       } 
>       return origEmit.apply(arguments)
>     }
>   })
> ```
> 
> If you're not ok with putting some wrapper around your queue processor and calling notice error there, we'd be open to your solution but it'd have to be an opt in feature to the recordSubscribedConsume API where you could pass in `handlePromiseError` but this is new territory for us and that message shim is already very complicated and would prefer it's handled in user code.

Thanks for the detailed reply.
When a job failed, we want the TransactionError to be recorded in the context of the transaction.
I thought about other solutions like shimming the handle failed job but that won't work either since the tx has already ended.

We have over 200 repos and thousands of message handlers. So adding noticeError wrapper around all our message handlers is not a simple task.
I'd prefer to proceed by adding another parameter to `recordSubscribedConsume`.

**Comment by bizob2828** [comment]
@benney-au-le sounds good. Maybe you can just provide a function called onPromiseReject and if it exists in the message shim call the function with error then you can do whatever you want in the function like in your case call noticeError.

**Comment by benney-au-le** [comment]
@bizob2828 is there any documentation for what the specification passed to `recordProduce`, `recordConsume` and `recordSubscribedConsume`?

If not are you able to start a document or improve the jsdoc; then when I add the new parameter I can update your document?

**Comment by bizob2828** [comment]
> @bizob2828 is there any documentation for what the specification passed to `recordProduce`, `recordConsume` and `recordSubscribedConsume`?
> 
> If not are you able to start a document or improve the jsdoc; then when I add the new parameter I can update your document?

They are defined in `lib/shim/specs.js`, but it looks like this part is a little involved.  The messageHandler copies information from the base spec, but it's kind of a mess 😬 .  Here's a [commit sha](https://github.com/bizob2828/node-newrelic/commit/400552d8ff5ecb8bb9cf52c4302f279bbbf6fa37) with all the code I think would be necessary to make this a backwards compatible, non-breaking change.  I did update my [example gist](https://gist.github.com/bizob2828/1f38b55d4b96fae69b0a89acae9c3ffe) and have verified it works.

**Comment by bizob2828** [comment]
@benney-au-le we are going to close this. But if you get some time to address my comments, please reopen and I can help get it landed

**Pull request closed without merging**
