### PR TITLE
Add Node.js 14 to CI jobs

### PR DESCRIPTION
**Pull request by jgeurts**
## Proposed Release Notes
* Add Node.js 14 support

## Links
#483
#329

## Details
* Adds Node.js 14 to CI jobs

### CODE REVIEW

**Comment by nijotz** [comment]
Hey Jim, thanks again for the PR! I noticed that you're working on this today and wanted to point out that we would like to keep Node 8 support until the next major release. So we would like to keep Node 8 versions tested until we've officially deprecated that support.

**Comment by nijotz** [comment]
If this PR was ONLY adding Node v14 support, we could merge it as soon as it's ready. But if removing Node v8 is included we'll need to hold off until we're ready for the next major release.

**Comment by jgeurts** [comment]
@nijotz Thanks for the clarification! I was going to knock out the Node 8 EOL from #483, but I'll leave that for someone else! :) I'll probably re-create this PR to squash the churn as I figure out how to get all of the tests to play nicely

**Comment by nijotz** [comment]
Sounds great, thanks for working with us!

**Pull request closed without merging**
