### PR TITLE
Fix the environment problem

### PR DESCRIPTION
**Pull request by umutc**
```
TypeError: cb is not a function
    at checkCandidate (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/environment.js:241:14)
    at Object.whilst (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:5220:10)
    at getLocalPackages (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/environment.js:239:5)
    at timeWrapper (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/environment.js:511:12)
    at /Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:3880:24
    at replenish (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:1011:17)
    at /Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:1016:9
    at _parallel (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit$1 [as parallelLimit] (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:3985:5)
    at findPackages (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/environment.js:466:5)
    at refresh (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/environment.js:582:5)
    at getJSON (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/environment.js:595:3)
    at /Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:3880:24
    at replenish (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:1011:17)
    at /Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:1041:24)
    at /Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:1046:16
    at eachOf (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:1117:5)
    at _parallel (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit [as parallel] (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/async/dist/async.js:3962:5)
    at facts (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/collector/facts.js:18:5)
    at CollectorAPI._getFacts (/Users/umutc/code/upwork/chip/ViewInFocus-Server/node_modules/newrelic/lib/collector/api.js:259:3)
```

### CODE REVIEW

**Comment by bizob2828** [comment]
@umutc thanks for contribution.  can you give us more context to the fix?  A repro case would be great.  It would be also good to write a unit test to prove this fixes the issue.  Let me know if you have any questions.

**Comment by umutc** [comment]
@bizob2828 its an express app written with typescript. The app is traditional MEAN stack app some info is below. It's a private repository so i will open new repository for a small representation of problem. Thanks for support.

---
some deps
"mongodb": "3.4.1",
"mongoose": "5.9.6",

---
engine 
"node": "14.18.2",
"npm": "6.14.15"

**Comment by bizob2828** [comment]
> @bizob2828 its an express app written with typescript. The app is traditional MEAN stack app some info is below. It's a private repository so i will open new repository for a small representation of problem. Thanks for support.
> 
> some deps "mongodb": "3.4.1", "mongoose": "5.9.6",
> 
> engine "node": "14.18.2", "npm": "6.14.15"

Ok, thanks. I suspect there's some conflict going on in your packages, specifically maybe the async lib.  The reason I say this is there should always be a callback in this place.  Can you show me the output of 

`npm ls async`

**Comment by umutc** [comment]
@bizob2828 

```├─┬ acl@0.4.11
│ └── async@2.6.3 
├─┬ bunyan-rotating-file-stream@1.6.3
│ └── async@1.5.2 
├─┬ express-jwt@5.3.1
│ └── async@1.5.2 
├─┬ mongoose-encryption@2.0.2
│ └── async@2.6.3  deduped
├─┬ newrelic@8.8.0 (github:umutc/node-newrelic#0d466d5bb95cd14104bb8d49c3b941632665e6bd)
│ └── async@3.2.3 
└─┬ nylas@3.0.0
  └── async@0.9.0 
```

**Comment by bizob2828** [comment]
@umutc thanks for providing the `npm ls` output for `async`.  Everything looks fine there.  Would you be able to provide a reproduction case so I could dig a little more?

**Comment by bizob2828** [comment]
I'm going to close this PR as I think there is something bigger going on in the customer's application.  If for some reason you can reproduce and provide steps we can reopen and talk through it

**Pull request closed without merging**
