### PR TITLE
ci: added PR title check automation

### PR DESCRIPTION
**Pull request by jmartin4563**
## Links
Closes NR-96233

## Details
Added a check to ensure that a PR title matches our Conventional Commit requirements, and if not, adds a comment to the PR listing our allowed prefixes. Note that we'll have to disable this workflow until we're ready to migrate to the new release flow.

**Comment Example**
Screenshot 2023-04-20 at 3 20 13 PM

### CODE REVIEW

**Review by bizob2828 — APPROVED** [review]
I'm not sure how to test these but LGTM

**Comment by jmartin4563** [comment]
> I'm not sure how to test these but LGTM

If you want to test, you can enable actions for your fork, then push this to a branch in your fork. Once you do that, create a PR in your fork, and you'll be able to test by editing the PR. This is how I tested to get the screenshot in the description.

**Comment by jmartin4563** [comment]
> > > I'm not sure how to test these but LGTM
> > 
> > 
> > If you want to test, you can enable actions for your fork, then push this to a branch in your fork. Once you do that, create a PR in your fork, and you'll be able to test by editing the PR. This is how I tested to get the screenshot in the description.
> 
> It's fine, I trust you. the only thing that occurs to me is that it doesn't fail the build, should we do that so we don't inadvertently merge a PR?

We absolutely will need to make it a required status check once we flip over to `release-please`, I'll add it to the migration ticket so we don't forget.

**Comment by bizob2828** [comment]
> > > > I'm not sure how to test these but LGTM
> > > 
> > > 
> > > If you want to test, you can enable actions for your fork, then push this to a branch in your fork. Once you do that, create a PR in your fork, and you'll be able to test by editing the PR. This is how I tested to get the screenshot in the description.
> > 
> > 
> > It's fine, I trust you. the only thing that occurs to me is that it doesn't fail the build, should we do that so we don't inadvertently merge a PR?
> 
> We absolutely will need to make it a required status check once we flip over to `release-please`, I'll add it to the migration ticket so we don't forget.

Maybe that screenshot is out of date but it says all checks are passing. Did you have an issue and the workflow commented on PR but then fixed?

**Comment by jmartin4563** [comment]
> > > > > I'm not sure how to test these but LGTM
> > > > 
> > > > 
> > > > If you want to test, you can enable actions for your fork, then push this to a branch in your fork. Once you do that, create a PR in your fork, and you'll be able to test by editing the PR. This is how I tested to get the screenshot in the description.
> > > 
> > > 
> > > It's fine, I trust you. the only thing that occurs to me is that it doesn't fail the build, should we do that so we don't inadvertently merge a PR?
> > 
> > 
> > We absolutely will need to make it a required status check once we flip over to `release-please`, I'll add it to the migration ticket so we don't forget.
> 
> Maybe that screenshot is out of date but it says all checks are passing. Did you have an issue and the workflow commented on PR but then fixed?

I get what you're saying now, I think because I'm adding a comment that I'm accidentally swallowing the error, will test a way to have the comment but still fail the build.

**Comment by jmartin4563** [comment]
> > > > > > I'm not sure how to test these but LGTM
> > > > > 
> > > > > 
> > > > > If you want to test, you can enable actions for your fork, then push this to a branch in your fork. Once you do that, create a PR in your fork, and you'll be able to test by editing the PR. This is how I tested to get the screenshot in the description.
> > > > 
> > > > 
> > > > It's fine, I trust you. the only thing that occurs to me is that it doesn't fail the build, should we do that so we don't inadvertently merge a PR?
> > > 
> > > 
> > > We absolutely will need to make it a required status check once we flip over to `release-please`, I'll add it to the migration ticket so we don't forget.
> > 
> > 
> > Maybe that screenshot is out of date but it says all checks are passing. Did you have an issue and the workflow commented on PR but then fixed?
> 
> I get what you're saying now, I think because I'm adding a comment that I'm accidentally swallowing the error, will test a way to have the comment but still fail the build.

Per our convo in Zoom, I accidentally took an outdated screenshot, everything is fine, this will have a failure even with the comment when the check actually fails

**Pull request merged**
