### PR TITLE
fix: Fixed instrumentation of Fastify via ESM

### LINKED ISSUE #2155: Newrelic + Fastify: Function.prototype.apply was called on #<Object>, which is an object and not a function
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We're converting our project from CJS to ESM, and are encountering some issues with Newrelic & its Fastify instrumentation.
Not sure if relevant, but we also integrate @apollo/server with fastify using https://www.npmjs.com/package/@as-integrations/fastify.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

```
{
  "error.message": "Function.prototype.apply was called on #<Object>, which is an object and not a function",
  "error.stack": "TypeError: Function.prototype.apply was called on #<Object>, which is an object and not a function\n    at wrappedFastifyModule (/.../node_modules/.pnpm/newrelic@11.15.0/node_modules/newrelic/lib/instrumentation/fastify.js:99:37)\n    at createFastifyInstance (file:///.../dist/src/utils/fastify/fastify.js:27:17)\n    at start (file:///.../dist/src/server.js:45:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
}
```

The above error is the main error message, but we're also seeing the following message since we migrated to ESM.

```
{
  "message": "New Relic for Node.js in worker_threads is not officially supported. Not starting! To bypass this, set `config.worker_threads.enabled` to true in configuration.",
}
```
How can it be that we didn't get this message before?

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

We encountered this when migrating our project from CJS to ESM. Everything worked fine before.

```
node --experimental-loader newrelic/esm-loader.mjs -r newrelic ./index.js
```

If/when I'm able to create a reproduction I can share, I will link it here.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Node version: `20.11.1`
Docker Image: `node:20.11.1-alpine`
Newrelic `11.15.0` (same error on `11.14.0`)
Fastify: `4.26.2`
@fastify/cors: `9.0.1`
@fastify/helmet: `11.1.1`
@fastify/type-provider-typebox: `4.0.0`
@apollo/server: `4.10.2`
@as-integrations/fastify: `2.1.1`
@newrelic/apollo-server-plugin: `5.1.0`

**newrelic.cjs**
```
module.exports.config = {
  agent_enabled: process.env.NEW_RELIC_LICENSE_KEY !== undefined,
  app_name: process.env.NEW_RELIC_APP_NAME,
  application_logging: {
    forwarding: {
      enabled: false,
    },
    local_decorating: {
      enabled: true
    },
  },
  distributed_tracing: {
    enabled: true,
  },
  ignore_server_configuration: true,
  labels: process.env.NEW_RELIC_LABELS,
  license_key: process.env.NEW_RELIC_LICENSE_KEY,
  logging: {
    level: 'warning',
    filepath: 'stdout',
  },
  slow_sql: {
    enabled: true,
  },
  transaction_tracer: {
    enabled: true,
    record_sql: 'obfuscated',
  },
};
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

### PR DESCRIPTION
**Pull request by jsumners-nr**
This resolves #2155.

### CODE REVIEW

**Review by bizob2828 — CHANGES_REQUESTED** [review]
I copied the tests to main of agent and they still pass. I'm not sure this reproduces the issue

**Comment by jsumners-nr** [comment]
> I copied the tests to main of agent and they still pass. I'm not sure this reproduces the issue

It _did_ reproduce it. But now it's not and I'm very confused.

**Review by bizob2828 — CHANGES_REQUESTED** [review]
Ok we talked IRL. I don't think this is the best place for this fix.  I traced this back to #1894 as the regression.  I think the fix should be [here](https://github.com/newrelic/node-newrelic/pull/1894/files#diff-3d0c4388e915f657046d7040af798b9376a45f953db048c457fe98a148d22b10R609).  That way we won't have code scattered that checks the `nrEsmProxy` symbol. Keep in mind and it'll be obvious because we test pg in esm but there's code in pg instrumentation that checks this symbol as well

**Comment by jsumners-nr** [comment]
This'll be my priority on 2024-04-25. Too late in the day to get into complicated work like this.

**Pull request closed without merging**
