### PR TITLE
Support for official DataStax Cassandra driver

### PR DESCRIPTION
**Pull request by asilvas**
The old `node-cassandra-cql` driver has been deprecated, so this takes its place, and includes support for statement tracking as well (modeled after MySQL driver).

The build & test system is a little more involved for integration tests than I was prepared to dedicate at this time, so I did not touch that piece. The tests should pretty much mimic that of the existing node-cassandra-cql driver.

### CODE REVIEW

**Comment by hayes** [comment]
Sorry for the lack of movement on this issue.  We are working on a big refactor of our database instrumentation, and it does not make sense to try to add a new instrumentation until that has been released.  I'll try to get this merged once our refactor is out.

**Comment by asilvas** [comment]
Any eta?

**Comment by hayes** [comment]
We released our big refactor yesterday, I am trying to make some time to look into this today

**Comment by wraithan** [comment]
Howdy, we totally forgot to close this out when we released support for the datastax driver. We added it in v1.17.1. I believe @hayes did a from scratch or copy from the `node-cassandra-cql` driver. He can go into further detail if needed.

**Pull request closed without merging**
