### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by RamyaPayyavula**
older versions of lodash has injection vulnerability. An attacker can inject malicious code via `sourceURL` since it is not sanitized for the user-provided code that leads to the `eval()` function.

### CODE REVIEW

**Comment by nijotz** [comment]
Just putting information here, it looks like we only use lodash here:

test/unit/high-security.test.js
test/integration/config/attribute-cat.tap.js

It's possible we could remove it as a dep as well.

**Comment by michaelgoin** [comment]
yeah, long-term i think removal will be nice to get away from the non-expoitable disclosure churn. but i'm fine with this PR just bumping deps.

**Comment by nijotz** [comment]
Double-checked on this, it looks like the tests are failing because the lockfile still has the old lodash version.

**Comment by nijotz** [comment]
#490 removes lodash as a dependency. Closing this in favor of that PR.

**Pull request closed without merging**
