### PR TITLE
test(travis): add node version 10

### PR DESCRIPTION
**Pull request by gergelyke**

### CODE REVIEW

**Comment by lykkin** [comment]
Hey, thanks for the PR!

We currently have our internal repo testing against v10, and it doesn't pass.  Right now the promise instrumentation seems to lose state in a few cases. We looking into shipping support for node 10 in the near future.

**Comment by gergelyke** [comment]
Ahh, I see - thanks for the heads up Bryan!

**Comment by finnp** [comment]
@lykkin Do you have an approx. date when newrelic will support Node 10?

**Comment by tanuck** [comment]
Is there any update on this yet? Node 10 has been out for some time now and it won't be long before it becomes the active LTS version.

**Comment by josdejong** [comment]
`newrelic@1.40.0` seems to work fine on Node 10, though that's not really a solution of course.

**Comment by NatalieWolfe** [comment]
@josdejong There were changes to Promises, Async Hooks, and the HTTP module in Node 10 which all subtly break the agent. The agent will not crash under these conditions, but the data reported is highly likely to be incorrect.

**Comment by josdejong** [comment]
Thanks for the update @NatalieWolfe, that sounds tricky. I hope you can solve it soon!

**Comment by psvet** [comment]
We should now have full Node 10 support as of `4.6.0`. Let us know if you run into any issues!

**Pull request closed without merging**
